[package]
name = "minipython-cli"
version = "0.1.0"
authors = ["SpacialCircumstances <SpacialCircumstances@users.noreply.github.com>"]
edition = "2018"

[dependencies]
minipython = { path = "../minipython" }
clap = "2.33.0"